/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrsRouteImport } from './routes/urs'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as AlvarasRouteImport } from './routes/alvaras'
import { Route as IndexRouteImport } from './routes/index'

const UrsRoute = UrsRouteImport.update({
  id: '/urs',
  path: '/urs',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const AlvarasRoute = AlvarasRouteImport.update({
  id: '/alvaras',
  path: '/alvaras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alvaras': typeof AlvarasRoute
  '/materiais': typeof MateriaisRoute
  '/obras': typeof ObrasRoute
  '/urs': typeof UrsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alvaras': typeof AlvarasRoute
  '/materiais': typeof MateriaisRoute
  '/obras': typeof ObrasRoute
  '/urs': typeof UrsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alvaras': typeof AlvarasRoute
  '/materiais': typeof MateriaisRoute
  '/obras': typeof ObrasRoute
  '/urs': typeof UrsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alvaras' | '/materiais' | '/obras' | '/urs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alvaras' | '/materiais' | '/obras' | '/urs'
  id: '__root__' | '/' | '/alvaras' | '/materiais' | '/obras' | '/urs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlvarasRoute: typeof AlvarasRoute
  MateriaisRoute: typeof MateriaisRoute
  ObrasRoute: typeof ObrasRoute
  UrsRoute: typeof UrsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urs': {
      id: '/urs'
      path: '/urs'
      fullPath: '/urs'
      preLoaderRoute: typeof UrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alvaras': {
      id: '/alvaras'
      path: '/alvaras'
      fullPath: '/alvaras'
      preLoaderRoute: typeof AlvarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlvarasRoute: AlvarasRoute,
  MateriaisRoute: MateriaisRoute,
  ObrasRoute: ObrasRoute,
  UrsRoute: UrsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
