/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as UrsRouteImport } from './routes/urs'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as MateriaisRouteImport } from './routes/materiais'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EncargosRouteImport } from './routes/encargos'
import { Route as ConsolidadoRouteImport } from './routes/consolidado'
import { Route as AlvarasRouteImport } from './routes/alvaras'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EncargosIndexRouteImport } from './routes/encargos.index'
import { Route as ObrasDiarioRouteImport } from './routes/obras_.diario'
import { Route as EncargosRelatoriosRouteImport } from './routes/encargos.relatorios'
import { Route as EncargosMedicoesRouteImport } from './routes/encargos.medicoes'
import { Route as EncargosLancamentosRouteImport } from './routes/encargos.lancamentos'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const UrsRoute = UrsRouteImport.update({
  id: '/urs',
  path: '/urs',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const MateriaisRoute = MateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EncargosRoute = EncargosRouteImport.update({
  id: '/encargos',
  path: '/encargos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolidadoRoute = ConsolidadoRouteImport.update({
  id: '/consolidado',
  path: '/consolidado',
  getParentRoute: () => rootRouteImport,
} as any)
const AlvarasRoute = AlvarasRouteImport.update({
  id: '/alvaras',
  path: '/alvaras',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EncargosIndexRoute = EncargosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EncargosRoute,
} as any)
const ObrasDiarioRoute = ObrasDiarioRouteImport.update({
  id: '/obras_/diario',
  path: '/obras/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const EncargosRelatoriosRoute = EncargosRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => EncargosRoute,
} as any)
const EncargosMedicoesRoute = EncargosMedicoesRouteImport.update({
  id: '/medicoes',
  path: '/medicoes',
  getParentRoute: () => EncargosRoute,
} as any)
const EncargosLancamentosRoute = EncargosLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => EncargosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alvaras': typeof AlvarasRoute
  '/consolidado': typeof ConsolidadoRoute
  '/encargos': typeof EncargosRouteWithChildren
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/materiais': typeof MateriaisRoute
  '/obras': typeof ObrasRoute
  '/urs': typeof UrsRoute
  '/usuarios': typeof UsuariosRoute
  '/encargos/lancamentos': typeof EncargosLancamentosRoute
  '/encargos/medicoes': typeof EncargosMedicoesRoute
  '/encargos/relatorios': typeof EncargosRelatoriosRoute
  '/obras/diario': typeof ObrasDiarioRoute
  '/encargos/': typeof EncargosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alvaras': typeof AlvarasRoute
  '/consolidado': typeof ConsolidadoRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/materiais': typeof MateriaisRoute
  '/obras': typeof ObrasRoute
  '/urs': typeof UrsRoute
  '/usuarios': typeof UsuariosRoute
  '/encargos/lancamentos': typeof EncargosLancamentosRoute
  '/encargos/medicoes': typeof EncargosMedicoesRoute
  '/encargos/relatorios': typeof EncargosRelatoriosRoute
  '/obras/diario': typeof ObrasDiarioRoute
  '/encargos': typeof EncargosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alvaras': typeof AlvarasRoute
  '/consolidado': typeof ConsolidadoRoute
  '/encargos': typeof EncargosRouteWithChildren
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/materiais': typeof MateriaisRoute
  '/obras': typeof ObrasRoute
  '/urs': typeof UrsRoute
  '/usuarios': typeof UsuariosRoute
  '/encargos/lancamentos': typeof EncargosLancamentosRoute
  '/encargos/medicoes': typeof EncargosMedicoesRoute
  '/encargos/relatorios': typeof EncargosRelatoriosRoute
  '/obras_/diario': typeof ObrasDiarioRoute
  '/encargos/': typeof EncargosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alvaras'
    | '/consolidado'
    | '/encargos'
    | '/login'
    | '/mapa'
    | '/materiais'
    | '/obras'
    | '/urs'
    | '/usuarios'
    | '/encargos/lancamentos'
    | '/encargos/medicoes'
    | '/encargos/relatorios'
    | '/obras/diario'
    | '/encargos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alvaras'
    | '/consolidado'
    | '/login'
    | '/mapa'
    | '/materiais'
    | '/obras'
    | '/urs'
    | '/usuarios'
    | '/encargos/lancamentos'
    | '/encargos/medicoes'
    | '/encargos/relatorios'
    | '/obras/diario'
    | '/encargos'
  id:
    | '__root__'
    | '/'
    | '/alvaras'
    | '/consolidado'
    | '/encargos'
    | '/login'
    | '/mapa'
    | '/materiais'
    | '/obras'
    | '/urs'
    | '/usuarios'
    | '/encargos/lancamentos'
    | '/encargos/medicoes'
    | '/encargos/relatorios'
    | '/obras_/diario'
    | '/encargos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlvarasRoute: typeof AlvarasRoute
  ConsolidadoRoute: typeof ConsolidadoRoute
  EncargosRoute: typeof EncargosRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MateriaisRoute: typeof MateriaisRoute
  ObrasRoute: typeof ObrasRoute
  UrsRoute: typeof UrsRoute
  UsuariosRoute: typeof UsuariosRoute
  ObrasDiarioRoute: typeof ObrasDiarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urs': {
      id: '/urs'
      path: '/urs'
      fullPath: '/urs'
      preLoaderRoute: typeof UrsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiais': {
      id: '/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof MateriaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encargos': {
      id: '/encargos'
      path: '/encargos'
      fullPath: '/encargos'
      preLoaderRoute: typeof EncargosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consolidado': {
      id: '/consolidado'
      path: '/consolidado'
      fullPath: '/consolidado'
      preLoaderRoute: typeof ConsolidadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alvaras': {
      id: '/alvaras'
      path: '/alvaras'
      fullPath: '/alvaras'
      preLoaderRoute: typeof AlvarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encargos/': {
      id: '/encargos/'
      path: '/'
      fullPath: '/encargos/'
      preLoaderRoute: typeof EncargosIndexRouteImport
      parentRoute: typeof EncargosRoute
    }
    '/obras_/diario': {
      id: '/obras_/diario'
      path: '/obras/diario'
      fullPath: '/obras/diario'
      preLoaderRoute: typeof ObrasDiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encargos/relatorios': {
      id: '/encargos/relatorios'
      path: '/relatorios'
      fullPath: '/encargos/relatorios'
      preLoaderRoute: typeof EncargosRelatoriosRouteImport
      parentRoute: typeof EncargosRoute
    }
    '/encargos/medicoes': {
      id: '/encargos/medicoes'
      path: '/medicoes'
      fullPath: '/encargos/medicoes'
      preLoaderRoute: typeof EncargosMedicoesRouteImport
      parentRoute: typeof EncargosRoute
    }
    '/encargos/lancamentos': {
      id: '/encargos/lancamentos'
      path: '/lancamentos'
      fullPath: '/encargos/lancamentos'
      preLoaderRoute: typeof EncargosLancamentosRouteImport
      parentRoute: typeof EncargosRoute
    }
  }
}

interface EncargosRouteChildren {
  EncargosLancamentosRoute: typeof EncargosLancamentosRoute
  EncargosMedicoesRoute: typeof EncargosMedicoesRoute
  EncargosRelatoriosRoute: typeof EncargosRelatoriosRoute
  EncargosIndexRoute: typeof EncargosIndexRoute
}

const EncargosRouteChildren: EncargosRouteChildren = {
  EncargosLancamentosRoute: EncargosLancamentosRoute,
  EncargosMedicoesRoute: EncargosMedicoesRoute,
  EncargosRelatoriosRoute: EncargosRelatoriosRoute,
  EncargosIndexRoute: EncargosIndexRoute,
}

const EncargosRouteWithChildren = EncargosRoute._addFileChildren(
  EncargosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlvarasRoute: AlvarasRoute,
  ConsolidadoRoute: ConsolidadoRoute,
  EncargosRoute: EncargosRouteWithChildren,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MateriaisRoute: MateriaisRoute,
  ObrasRoute: ObrasRoute,
  UrsRoute: UrsRoute,
  UsuariosRoute: UsuariosRoute,
  ObrasDiarioRoute: ObrasDiarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
