// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrvplahmthguvrauzwpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydnBsYWhtdGhndXZyYXV6d3B5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NjI3OTYsImV4cCI6MjA5MjQzODc5Nn0.D4jRJ2zXY8qIGLBik0nhAR7uVzOKOVCoFFUKwWoMKuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});